# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'popular wikis list' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for popular wikis list
  pod 'Kingfisher'
  pod 'SnapKit'
  
  target 'popular wikis listTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'popular wikis listUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
